name: 02 - Workflows Event
on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show the tigger
              run: echo "Trigger by event ${{ github.event_name }}"

